# Learn more about it here: https://github.com/marketplace/actions/deploy-mkdocs
# and here: https://www.mkdocs.org/user-guide/deploying-your-docs/#github-pages

name: Publish docs via GitHub Pages
on:
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        
      - name: install mkdocs
        run: echo 'mkdocs' > requirements.txt  

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@nomaterial
        # Or use mhausenblas/mkdocs-deploy-gh-pages@master to build with the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CUSTOM_DOMAIN: optionaldomain.com
          # CONFIG_FILE: folder/mkdocs.yml
          # EXTRA_PACKAGES: build-base
          # GITHUB_DOMAIN: github.myenterprise.com
