name: Build and deploy Dokka to GitHub Pages


on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - uses: gradle/gradle-build-action@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build html
        run: ./gradlew dokkaHtml --no-daemon --stacktrace
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: documentation


  deploy:
    name : Deploy 🚀
    needs: [build-page]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: documentation
          path: documentation
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: documentation # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
