# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gradle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew    
    - name: Unit tests
      run: bash ./gradlew test --stacktrace
    - name: Run Tests
      run: ./gradlew test
    - name: Build Project
      run: ./gradlew assemble
    - name: Build Debug APK
      run: bash ./gradlew :app:assembleDebug
    - name: build release
      run: ./gradlew assembleRelease
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: SocyMusic
        path: app/build/outputs/apk/release/SocyMusic.apk     
