name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to SocyMusic and thank you for submitting anew issue, we will try to help you as soon as possible. In the meantime, if you manage to solve the issue yourself please update your issue so that people in the future with the same problem could find it useful'
        pr-message: 'Welcome to SocyMusic and thank you for contributing to the project! Make sure you included as much information as possible, this will assure your pull request will be seen as useful and actually merged in the end.'
